n=int(input("dati un nr"))
print("1x",n,"=",1*n,sep="")
print("2x",n,"=",2*n,sep="")
print("3x",n,"=",3*n,sep="")
print("4x",n,"=",4*n,sep="")
print("5x",n,"=",5*n,sep="")
print("6x",n,"=",6*n,sep="")
print("7x",n,"=",7*n,sep="")
print("8x",n,"=",8*n,sep="")
print("9x",n,"=",9*n,sep="")