#de la tastatura se introduce nr de rand al curcubeului.De afisat denumirea culorilor.
n=int(input("dati nr culorii"))
if n==1:print("Rosu")
if n==2:print("oranj")
if n==3:print("galben")
if n==4:print("verde")
if n==5:print("albastru")
if n==6:print("indigo")
if n==7:print("violet")
if((n>7) or (n<1)):print("curcubeul are 7 culori")